# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import bioSequencesService_pb2 as bioSequencesService__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bioSequencesService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class biosequenceservicesStub(object):
    """service to expose a remote method
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.receive_sequeces = channel.unary_unary(
                '/bio_sequence_services.biosequenceservices/receive_sequeces',
                request_serializer=bioSequencesService__pb2.StoreNucleotid_processeSequences.SerializeToString,
                response_deserializer=bioSequencesService__pb2.ResponseStore.FromString,
                _registered_method=True)
        self.nucleotid_processesToCodons = channel.unary_unary(
                '/bio_sequence_services.biosequenceservices/nucleotid_processesToCodons',
                request_serializer=bioSequencesService__pb2.TransformFromNucleotid_processesToCodons.SerializeToString,
                response_deserializer=bioSequencesService__pb2.ResponseTransformNToC.FromString,
                _registered_method=True)
        self.codonToProtain = channel.unary_unary(
                '/bio_sequence_services.biosequenceservices/codonToProtain',
                request_serializer=bioSequencesService__pb2.traductionToProtein.SerializeToString,
                response_deserializer=bioSequencesService__pb2.ResponsetraductionToProtein.FromString,
                _registered_method=True)
        self.getDataset = channel.unary_unary(
                '/bio_sequence_services.biosequenceservices/getDataset',
                request_serializer=bioSequencesService__pb2.Dataset.SerializeToString,
                response_deserializer=bioSequencesService__pb2.ResponsegetDataset.FromString,
                _registered_method=True)


class biosequenceservicesServicer(object):
    """service to expose a remote method
    """

    def receive_sequeces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def nucleotid_processesToCodons(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def codonToProtain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_biosequenceservicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'receive_sequeces': grpc.unary_unary_rpc_method_handler(
                    servicer.receive_sequeces,
                    request_deserializer=bioSequencesService__pb2.StoreNucleotid_processeSequences.FromString,
                    response_serializer=bioSequencesService__pb2.ResponseStore.SerializeToString,
            ),
            'nucleotid_processesToCodons': grpc.unary_unary_rpc_method_handler(
                    servicer.nucleotid_processesToCodons,
                    request_deserializer=bioSequencesService__pb2.TransformFromNucleotid_processesToCodons.FromString,
                    response_serializer=bioSequencesService__pb2.ResponseTransformNToC.SerializeToString,
            ),
            'codonToProtain': grpc.unary_unary_rpc_method_handler(
                    servicer.codonToProtain,
                    request_deserializer=bioSequencesService__pb2.traductionToProtein.FromString,
                    response_serializer=bioSequencesService__pb2.ResponsetraductionToProtein.SerializeToString,
            ),
            'getDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.getDataset,
                    request_deserializer=bioSequencesService__pb2.Dataset.FromString,
                    response_serializer=bioSequencesService__pb2.ResponsegetDataset.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bio_sequence_services.biosequenceservices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bio_sequence_services.biosequenceservices', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class biosequenceservices(object):
    """service to expose a remote method
    """

    @staticmethod
    def receive_sequeces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bio_sequence_services.biosequenceservices/receive_sequeces',
            bioSequencesService__pb2.StoreNucleotid_processeSequences.SerializeToString,
            bioSequencesService__pb2.ResponseStore.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def nucleotid_processesToCodons(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bio_sequence_services.biosequenceservices/nucleotid_processesToCodons',
            bioSequencesService__pb2.TransformFromNucleotid_processesToCodons.SerializeToString,
            bioSequencesService__pb2.ResponseTransformNToC.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def codonToProtain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bio_sequence_services.biosequenceservices/codonToProtain',
            bioSequencesService__pb2.traductionToProtein.SerializeToString,
            bioSequencesService__pb2.ResponsetraductionToProtein.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bio_sequence_services.biosequenceservices/getDataset',
            bioSequencesService__pb2.Dataset.SerializeToString,
            bioSequencesService__pb2.ResponsegetDataset.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
